<?php

namespace ContainerLgntZfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PgbKoDSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pgbKoDS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pgbKoDS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'intern' => ['privates', '.errored..service_locator.pgbKoDS.App\\Entity\\Intern', NULL, 'Cannot autowire service ".service_locator.pgbKoDS": it needs an instance of "App\\Entity\\Intern" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'intern' => 'App\\Entity\\Intern',
        ]);
    }
}
