<?php

namespace ContainerLgntZfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YAPgSe1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yAPgSe1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yAPgSe1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\InternController::delete' => ['privates', '.service_locator.pgbKoDS', 'get_ServiceLocator_PgbKoDSService', true],
            'App\\Controller\\InternController::edit' => ['privates', '.service_locator.pgbKoDS', 'get_ServiceLocator_PgbKoDSService', true],
            'App\\Controller\\InternController::exportInternPdfSingle' => ['privates', '.service_locator.g0q2sRj', 'get_ServiceLocator_G0q2sRjService', true],
            'App\\Controller\\InternController::exportInternsPdf' => ['privates', '.service_locator.WUMLObY', 'get_ServiceLocator_WUMLObYService', true],
            'App\\Controller\\InternController::index' => ['privates', '.service_locator.jMtoq55', 'get_ServiceLocator_JMtoq55Service', true],
            'App\\Controller\\InternController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\InternController::show' => ['privates', '.service_locator.joIn95u', 'get_ServiceLocator_JoIn95uService', true],
            'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\InternController:delete' => ['privates', '.service_locator.pgbKoDS', 'get_ServiceLocator_PgbKoDSService', true],
            'App\\Controller\\InternController:edit' => ['privates', '.service_locator.pgbKoDS', 'get_ServiceLocator_PgbKoDSService', true],
            'App\\Controller\\InternController:exportInternPdfSingle' => ['privates', '.service_locator.g0q2sRj', 'get_ServiceLocator_G0q2sRjService', true],
            'App\\Controller\\InternController:exportInternsPdf' => ['privates', '.service_locator.WUMLObY', 'get_ServiceLocator_WUMLObYService', true],
            'App\\Controller\\InternController:index' => ['privates', '.service_locator.jMtoq55', 'get_ServiceLocator_JMtoq55Service', true],
            'App\\Controller\\InternController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\InternController:show' => ['privates', '.service_locator.joIn95u', 'get_ServiceLocator_JoIn95uService', true],
            'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\InternController::delete' => '?',
            'App\\Controller\\InternController::edit' => '?',
            'App\\Controller\\InternController::exportInternPdfSingle' => '?',
            'App\\Controller\\InternController::exportInternsPdf' => '?',
            'App\\Controller\\InternController::index' => '?',
            'App\\Controller\\InternController::new' => '?',
            'App\\Controller\\InternController::show' => '?',
            'App\\Controller\\SecurityController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\InternController:delete' => '?',
            'App\\Controller\\InternController:edit' => '?',
            'App\\Controller\\InternController:exportInternPdfSingle' => '?',
            'App\\Controller\\InternController:exportInternsPdf' => '?',
            'App\\Controller\\InternController:index' => '?',
            'App\\Controller\\InternController:new' => '?',
            'App\\Controller\\InternController:show' => '?',
            'App\\Controller\\SecurityController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
