<?php

namespace ContainerLgntZfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInternService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.g0q2sRj.App\Entity\Intern' shared service.
     *
     * @return \App\Entity\Intern
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.g0q2sRj": it needs an instance of "App\\Entity\\Intern" but this type has been excluded in "config/services.yaml".');
    }
}
