<?php

namespace ContainerLgntZfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInternControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InternController' shared autowired service.
     *
     * @return \App\Controller\InternController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InternController.php';

        $container->services['App\\Controller\\InternController'] = $instance = new \App\Controller\InternController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InternController', $container));

        return $instance;
    }
}
