<?php

namespace ContainerLgntZfY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfSingleExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PdfSingleExportService' shared autowired service.
     *
     * @return \App\Service\PdfSingleExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PdfSingleExportService.php';

        return $container->privates['App\\Service\\PdfSingleExportService'] = new \App\Service\PdfSingleExportService();
    }
}
