<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLgntZfY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLgntZfY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLgntZfY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLgntZfY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLgntZfY\App_KernelDevDebugContainer([
    'container.build_hash' => 'LgntZfY',
    'container.build_id' => '99d7e6e2',
    'container.build_time' => 1715775240,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLgntZfY');
